name: rentcon
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.3+3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  line_awesome_flutter: ^3.0.1
  mongo_dart: ^0.10.3
  http:
  shared_preferences: ^2.3.2
  jwt_decoder:
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  loading_indicator: ^3.1.1
  sliding_up_panel: ^2.0.0+1
  gif: ^2.3.0
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.69.0
  intl: ^0.19.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  faker: ^2.2.0
  animated_splash_screen: ^1.3.0
  badges: ^3.1.2
  table_calendar: ^3.1.2
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  google_nav_bar: ^5.0.6
  blur: ^4.0.0
  shadcn_flutter: ^0.0.20
  shadcn_ui: ^0.9.7
  socket_io_client: ^3.0.0
  permission_handler: ^11.3.1
  flare_flutter: ^3.0.2
  rive: ^0.13.14
  app_links: ^6.2.0 
  url_launcher: ^6.3.1
  saver_gallery: ^3.0.6
  day_night_switch: ^1.0.4
  animated_theme_switcher: ^2.0.10
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  page_transition: ^2.1.0
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.2
  provider: ^6.1.2
  tutorial_coach_mark: ^1.2.11
  flutter_email_sender: ^6.0.3
  onesignal_flutter: ^5.2.6
  percent_indicator: ^4.2.3
  awesome_snackbar_content: ^0.1.4
  cached_network_image: ^3.4.1
  calendar_view: ^1.2.0
  timelines_plus: ^1.0.3
  animations: ^2.0.11
  timeline_tile: ^2.0.0
  custom_refresh_indicator: ^4.0.1
  package_info_plus: ^8.1.0
  video_player: ^2.9.2
  file_picker: ^8.1.3




flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "assets/icons/android12below.png"


  android_12:
    color: "#ffffff"
    image: "assets/icons/android12above.png"


flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"
  image_path: "assets/icons/logo.png"
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the Cuper~~"tinoIcons class for iOS style icons.
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

     - assets/images/
     - assets/icons/
     - assets/icons/ren.png
     - assets/icons/ren2.png
     - assets/flares/checkmark_circle.riv
     - assets/flares/checkmark.riv    
     - assets/flares/alert_icon.riv
     - assets/flares/empty.riv
     - assets/flares/button_success.riv
     - assets/icons/lottie.json
     - assets/icons/manage.png
     - assets/icons/animrent.lottie
     - assets/icons/rentcon.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Light.ttf
          weight: 300

    - family: RadixIcons
      fonts:
        - asset: "packages/shadcn_flutter/icons/RadixIcons.otf"
    - family: BootstrapIcons
      fonts:
        - asset: "packages/shadcn_flutter/icons/BootstrapIcons.otf"
    - family: "GeistSans"
      fonts:
        - asset: "packages/shadcn_flutter/fonts/Geist-Black.otf"
          weight: 800
        - asset: "packages/shadcn_flutter/fonts/Geist-Bold.otf"
          weight: 700
        - asset: "packages/shadcn_flutter/fonts/Geist-Light.otf"
          weight: 300
        - asset: "packages/shadcn_flutter/fonts/Geist-Medium.otf"
          weight: 500
        - asset: "packages/shadcn_flutter/fonts/Geist-SemiBold.otf"
          weight: 600
        - asset: "packages/shadcn_flutter/fonts/Geist-Thin.otf"
          weight: 100
        - asset: "packages/shadcn_flutter/fonts/Geist-UltraBlack.otf"
          weight: 900
        - asset: "packages/shadcn_flutter/fonts/Geist-UltraLight.otf"
          weight: 200
        - asset: "packages/shadcn_flutter/fonts/Geist-Regular.otf"
          weight: 400
    - family: "GeistMono"
      fonts:
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Black.otf"
          weight: 800
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Bold.otf"
          weight: 700
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Light.otf"
          weight: 300
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Medium.otf"
          weight: 500
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Regular.otf"
          weight: 400
        - asset: "packages/shadcn_flutter/fonts/GeistMono-SemiBold.otf"
          weight: 600
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Thin.otf"
          weight: 100
        - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraBlack.otf"
          weight: 900
        - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraLight.otf"
          weight: 200




