//final url = 'https://rentconnect-backend-nodejs.onrender.com/';
final url = 'http://192.168.1.13:3000/';
final registration = url + "registration";
final login = url + 'login';
final storeProperty = url + 'storeProperty';
final getProperty = url + 'getUserPropertyList';
final getUserEmail = url + 'getUserEmail';
final getAllProperties = url + 'getAllProperties';
final getUserBookmarks = url + 'getUserBookmarks';